version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: postgres
    env_file: .env # Load environment variables from .env file
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - kryptos-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    command: ["postgres", "-c", "ssl=off"]

  rest-api:
    build:
      context: ./backend/rest-api
      dockerfile: Dockerfile
    container_name: rest-api
    ports:
      - "8080:8080"
    volumes:
      - ./backend/rest-api:/app
    networks:
      - kryptos-network
    env_file: .env # Load environment variables from .env file
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST} # Should resolve to "postgres"
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSLMODE=disable
    depends_on:
      - postgres

  worker-server:
    build:
      context: ./backend/worker-server
      dockerfile: Dockerfile
    container_name: worker-server
    ports:
      - "8081:8080"
    volumes:
      - ./backend/worker-server:/app
    networks:
      - kryptos-network
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSLMODE=disable
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      # Uncomment the following line for HTTPS on port 443
      # - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs # If you are using SSL certificates (for production)
    networks:
      - kryptos-network
    depends_on:
      - rest-api

networks:
  kryptos-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
